version: '3'
services:

    db:
        container_name: db
        image: mysql:5.6
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: "test"
        ports:
            - 3307:3306

    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        depends_on:
            - db
        image: symfony
        ports:
            - 8001:8000
        volumes:
            - .:/app/
        environment:
            DATABASE_URL: "mysql://root:test@db:3306/db_sf45"
        command: >
            sh -c "php bin/console doctrine:database:create &&
            php bin/console doctrine:schema:update --force &&
            php -S 0.0.0.0:8000 public/index.php"

    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080

